# Generated by Django 4.1 on 2022-09-02 11:54

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customermodel',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Unitmodel',
            fields=[
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Productmodel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.unitmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Ordermodel',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=30)),
                ('order_date', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailsmodel',
            fields=[
                ('order_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('get_product', models.CharField(max_length=50)),
                ('get_unit', models.CharField(max_length=50)),
                ('get_product_total', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('get_quantity', models.PositiveIntegerField(default=1)),
                ('get_total_product_price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ordermodel')),
            ],
        ),
    ]
