# Generated by Django 4.1 on 2022-09-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
